export const STRINGS = {
  createDAO: "Create your DAO using aragonOSx 🦅",
  DAOlogo: "Your DAO\'s logo",
  DAOname: "What\'s the name of your DAO?",
  DAOdescription: "Add a brief description of your DAO, but remember, this will be stored on-chain. It can only be changed afterwards through a proposal.",
  DAOwebsite: "Your DAOs Website (if you have any)",
  describeYourDAO: "Describe your DAO",
  dragndrop: "or drag and drop",
  placeholderDescription: "We are solving x problem through y solution!",
  placeholderName: "My DAO",
  placeholderWebsite: "www.exampleDAO.com",
  fileMetrics: "PNG, JPG, GIF up to 10MB",
  http: "http://",
  save: "Save",
  uploadFile: "Upload a file",
}
