import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import CreateDAOForm from './components/CreateDAOForm';
import LandingPage from './LandingPage';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aragon DAO</title>
        <meta
          name="description"
          content="This is a tutorial generated by the Aragon team to help you get started with Aragon SDK."
        />
        {/* TO-DO: Get Aragon's Favicon */}
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <main className={styles.main}>
        <LandingPage />
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
